name: License Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  license-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      run: |
        sudo apt-get update && sudo apt-get upgrade -y
        sudo add-apt-repository ppa:deadsnakes/ppa --yes
        sudo apt-get install python3.8 python3.8-venv python3.8-distutils -y
        sudo apt-get install -y python3-pip

    - name: Set up Python Virtual Environment
      run: |
        /usr/bin/python3.8 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel

    - name: Install ScanCode Toolkit via pip
      run: |
        source venv/bin/activate
        pip install scancode-toolkit

    - name: Run ScanCode
      run: |
        source venv/bin/activate
        scancode --license --json-pp output.json packages

    - name: Analyze License Output
      run: |
        source venv/bin/activate
        python3 analyze_license.py

    - name: Upload Scan Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: license-scan-report
        path: output.json
